- redshift/resource_redshift_user.go
- redshift/resource_redshift_user_test.go
When deleting a user, the provider attempts to chown all of the user's objects to `$REDSHIFT_USER`. If you use temporary credentials provided by [GetClusterCredentials](https://docs.aws.amazon.com/redshift/latest/APIReference/API_GetClusterCredentials.html) the username you need to authenticate as is prefixed with either `IAM:` or `IAMA:`. However, the username needed for the chown is the non-prefixed one.
This PR fixes the issue by stripping these specific prefixes from the chown statements (and also parameterizes them).
You can reproduce the error like so:
```bash
username=<your db username>
clusterIdentifier=<redshift cluster identifier>
credentials="$(aws redshift get-cluster-credentials --db-user=$username --cluster-identifier=$clusterIdentifier)"
export REDSHIFT_USER="$(echo …
```
> Fix error changing ownership when deleting a user, if the current user has temporary credentials

- redshift/config.go
- redshift/resource_redshift_user.go
- redshift/resource_redshift_user_test.go
Per https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_USER.html:
>As a more secure alternative to passing the CREATE USER password parameter as clear text, you can specify an MD5 hash of a string that includes the password and user name.
>
>**Note**
>When you specify an MD5 hash string, the CREATE USER command checks for a valid MD5 hash string, but it doesn't validate the password portion of the string. It is possible in this case to create a password, such as an empty string, that you can't use to log on to the database.
>
>To specify an MD5 password, follow these steps:
>
>1. Concatenate the password and user name.
>For example, for password `ez` and user `user1`, the concatenated string is `ezuser1`.
>
>2. Convert the concatenated string into a 32-character MD5 hash string. You …
> Use md5 hashing for redshift_user passwords

- redshift/provider.go
- redshift/provider_test.go
Fix an error which occurs when REDSHIFT_USERNAME is the prefixed value from GetClusterCredentials.
This may only occur during tests but still probably needs to be fixed.
Fix panic when neither password nor temporary_credentials is configured.
Also simplify how we fetch temporary credentials.
> Bug fixes related to temporary credentials

- docs/index.md
- redshift/provider.go
Fixed typo in ` redshift/provider.go`: changed from `your` to `you` in line 88.
> Fix typo `provider.go`

- docs/data-sources/schema.md
- docs/resources/schema.md
- examples/resources/redshift_schema/resource.tf
- redshift/acc_test.go
- redshift/custom_diff.go
- redshift/data_source_redshift_schema.go
- redshift/data_source_redshift_schema_test.go
- redshift/helpers.go
- redshift/provider_test.go
- redshift/resource_redshift_schema.go
- redshift/resource_redshift_schema_test.go
This PR extends the `redshift_schema` resource and data source to support all of the available flavours of external schema documented at https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_EXTERNAL_SCHEMA.html. There is a new nested configuration block in the `redshift_schema` resource, named `external_schema`.
Supported external schema sources are:
* `data_catalog_source` for AWS Glue Data Catalog
* `hive_metastore_source` for a Hive metastore (I think really it only supports EMR but I haven't tested it as I don't have a Hadoop environment to test against, EMR or otherwise)
* `rds_postgres_source` for federated query against RDS/Aurora PostgreSQL
* `rds_mysql_source` for federated query against RDS/Aurora MySQL (note that this is currently a Preview feature and thus subject to …
> Add external schema support

- README.md
- docs/index.md
- go.mod
- redshift/config.go
- redshift/proxy_driver.go
- templates/index.md.tmpl
This PR registers a custom driver name for pq, per https://github.com/lib/pq/issues/470#issuecomment-227517227, and uses it to override the default dialer with one that can transparently handle socks proxy configuration through environment variables.
The environment variable is named `ALL_PROXY` (`all_proxy` also works) and has the format `socks5[h]://[<socks-user>:<socks-password>@]<socks-host>[:<socks-port>]`
There is also support for a `NO_PROXY`/`no_proxy` environment variable which lists hostnames, IP addresses, CIDR blocks, and wildcard domain names which should not go through the proxy.
> Support connecting through a socks proxy

- redshift/helpers.go
- redshift/provider.go
- redshift/resource_redshift_grant.go
- redshift/resource_redshift_grant_test.go
The second part in resolving #15.
> Add `redshift_grant` resource

- redshift/resource_redshift_grant.go
- redshift/resource_redshift_grant_test.go
Group privileges were incorrectly read when there was a user with the same name as a group due to the missing 'group ' prefix in ACL.
This is based on #25 with additional fixes for Schema and Database privileges which were also affected.
> Fix reading group grant privileges

- redshift/resource_redshift_grant.go
> Extend grant detection also to views and materialized views.

- redshift/resource_redshift_schema.go
- redshift/resource_redshift_schema_test.go
It will now correctly apply only at create time of the resource.
Fixes #27
> Rewrite DiffSuppressFunc for create_external_database_if_not_exists.

- redshift/helpers.go
- redshift/helpers_test.go
- redshift/resource_redshift_default_privileges.go
- redshift/resource_redshift_default_privileges_test.go
- redshift/resource_redshift_grant.go
- redshift/resource_redshift_grant_test.go
- redshift/resource_redshift_privilege.go
- redshift/validation.go
Adding `DROP` privilege for table objects;
https://docs.aws.amazon.com/redshift/latest/dg/r_GRANT.html
> feat: Add drop privilege for table objects.

- redshift/resource_redshift_privilege.go
`redshift_privilege` is buggy and has been superseded by `redshift_grant` + `redshift_default_privilege`. This PR adds a deprecation message to the resource.
> Deprecate redshift_privilege resource

- redshift/resource_redshift_user.go
- redshift/resource_redshift_user_test.go
Found as a tip in the Terraform community forums, that you can use the `CustomizeDiff` function to validate related attributes on the plan phase. The drawback is that this will not be picked by `terraform validate` but still better than this being errored at apply phase.
> Move the superuser/password validation to CustomizeDiff func

- redshift/resource_redshift_group.go
- redshift/resource_redshift_user.go
AWS Redshift recently released a Role-based Access Control(RBAC) feature, which simplifies the managing of security privileges with Amazon Redshift.
RBAC doesn't support CASCADE parameter when modifying privileges by using REVOKE and ALTER DEFAULT PRIVILEGES.
> Remove CASCADE from ALTER DEFAULT when dropping users and groups

- redshift/resource_redshift_grant.go
- redshift/resource_redshift_grant_test.go
Currently, there is a risk of obtaining redshift_grant resources having identical id. This fix allows to avoid it.
> Fixed non-unique ids in redshift_grant possible

- redshift/resource_redshift_grant.go
- redshift/resource_redshift_grant_test.go
- redshift/resource_redshift_privilege.go
This PR adds support for users in the `redshift_grant` resource. Adds new `user` key to the schema. The key will conflict with the `group` key and at the same time, one of `group` or `user` keys is mandatory.
Implements feature request from #23
> Support for users in redshift_grant resource

- redshift/resource_redshift_default_privileges.go
- redshift/resource_redshift_default_privileges_test.go
This PR adds support for users in the `redshift_default_privileges` resource. Adds new `user` key to the schema. The key will conflict with the `group` key and at the same time, one of `group` or `user` keys is mandatory.
> Support for users in redshift_default_privileges resources

- docs/index.md
- redshift/provider.go
When calling `GetClusterCredentials`, users must supply the region where the Redshift cluster is located. Currently, there is no explicit provider configuration field for this input. As noted in https://github.com/brainly/terraform-provider-redshift/issues/58#issuecomment-1060708054, you can use `AWS_REGION` to set this.
I checked the AWS provider and mirrored its simple field implementation, with no validation:
https://github.com/hashicorp/terraform-provider-aws/blob/19469514cc16736d80ab976aa3178d5aaedbeba8/internal/provider/provider.go#L292-L297
> Add `region` support when calling `GetClusterCredentials`

- redshift/resource_redshift_user.go
- redshift/resource_redshift_user_test.go
Currently, it's not possible to define configuration like this:
```tf
resource "redshift_user" "terraform" {
name      = "terraform"
superuser = true
password  = random_password.terraform.result
}
resource "random_password" "terraform" {
length      = 64
min_lower   = 1
min_upper   = 1
min_numeric = 1
}
```
Given this configuration, the provider returns an error:
```
Users that are superusers must define a password.
```
Upon further investigation, this error is returned from `CustomizeDiff`. This hook runs before a plan is rendered. This means that on first run, before the `Create` method for `random_password` has run, the value for `result` is not yet known.
`GetOk` will still return `_, true`, because it is known that some value is set. When the value is unknown, `Get` will return the …
> `user`: handle unknown superuser passwords

- redshift/resource_redshift_group.go
When there is no dependency between user and group or user is in
multiple groups and was removed before then terraform will fail. After this
commit we fix problem and during alter table we check if user still
exists in redshift.
> Before alter group make sure user still exists

- redshift/resource_redshift_database.go
- redshift/resource_redshift_group.go
- redshift/resource_redshift_group_test.go
> Preserve user names case in group membership list and database owner attribute

- redshift/resource_redshift_group.go
- redshift/resource_redshift_group_test.go
A fix to allow removing existing users from groups.
The added test case replicates an error reported by @tripolif98 in #79. 
```
=== RUN   TestAccRedshiftGroup_RemoveExistingUser
resource_redshift_group_test.go:145: Step 2/2 error: Error running apply: exit status 1
Error: error reading info about user: %!s(<nil>)
with redshift_group.group,
on terraform_plugin_test.tf line 2, in resource "redshift_group" "group":
2: resource "redshift_group" "group" {
--- FAIL: TestAccRedshiftGroup_RemoveExistingUser (13.19s)
FAIL
FAIL    github.com/brainly/terraform-provider-redshift/redshift 13.200s
FAIL
```
After fix to the `switch` statement is applied, the test passes.
```
=== RUN   TestAccRedshiftGroup_RemoveExistingUser
--- PASS: TestAccRedshiftGroup_RemoveExistingUser (16.52s)
PASS
ok …
```
> Fix removing existing users from groups

- docs/resources/datashare_privilege.md
- examples/resources/redshift_datashare_privilege/resource.tf
Changes:
* rename within_account to cross_account for cross-account datashare permission example
* "terraform fmt" examples
* rename "name" to "share_name"
> Improve docs for redshift_datashare_privilege resource

- CHANGELOG.md
- redshift/resource_redshift_default_privileges.go
- redshift/resource_redshift_default_privileges_test.go
- redshift/resource_redshift_grant.go
- redshift/resource_redshift_grant_test.go
- redshift/resource_redshift_group_test.go
Addresses https://github.com/brainly/terraform-provider-redshift/issues/94
> Fix - preventing from non-idempotent reapplying grants for entities with ascii chars 33-126 in their names

- redshift/data_source_redshift_user.go
- redshift/data_source_redshift_user_test.go
- redshift/resource_redshift_grant.go
- redshift/resource_redshift_user.go
- redshift/resource_redshift_user_test.go
This PR 
- adds support of SESSION TIMEOUT user settinghttps://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_USER.html
-  adds missing rows.Close() in order to avoid condition where connection is kept open and idle due to not closed result set. 
With larger set of in this case grants it could result with threads waiting for result set cleanup that never occurred.
> Add SESSION TIMEOUT support and missing defer rows.Close()

- redshift/resource_redshift_user.go
This PR fixes condition of userSessionTimeoutAttr that results with skipping session timeout parameter during user creation.
> Fix userSessionTimeoutAttr condition
